-- =====================================================
-- Complete Database Schema for E-Commerce Admin Application
-- =====================================================
-- This file contains the complete database schema for the e-commerce admin system
-- Includes: Admin, Categories, Products, Orders, Customers, and Storage
-- =====================================================

-- =====================================================
-- ADMIN TABLES
-- =====================================================

-- Admin Users Table
CREATE TABLE admins (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    role VARCHAR(20) DEFAULT 'admin' CHECK (role IN ('super_admin', 'admin', 'moderator')),
    is_active BOOLEAN DEFAULT TRUE,
    last_login TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Admin Sessions Table (for authentication)
CREATE TABLE admin_sessions (
    id SERIAL PRIMARY KEY,
    admin_id INT NOT NULL,
    session_token VARCHAR(255) UNIQUE NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (admin_id) REFERENCES admins(id) ON DELETE CASCADE
);

-- Admin Activity Log Table
CREATE TABLE admin_activity_log (
    id SERIAL PRIMARY KEY,
    admin_id INT NOT NULL,
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(50) NOT NULL, -- 'product', 'category', 'order', etc.
    entity_id VARCHAR(50) NULL,
    old_values JSONB NULL,
    new_values JSONB NULL,
    ip_address VARCHAR(45) NULL,
    user_agent TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (admin_id) REFERENCES admins(id) ON DELETE CASCADE
);

-- =====================================================
-- CATEGORIES TABLE
-- =====================================================

CREATE TABLE IF NOT EXISTS categories (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    description TEXT NULL,
    image_url VARCHAR(500) NULL,
    status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =====================================================
-- PRODUCTS TABLE (Inferred from API usage)
-- =====================================================

CREATE TABLE IF NOT EXISTS products (
    id TEXT PRIMARY KEY, -- Product ID as string (e.g., 'lp-001', 'sp-001')
    name TEXT NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL CHECK (price >= 0),
    category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,
    subcategory TEXT,
    image TEXT,
    rating DECIMAL(3, 2) DEFAULT 0 CHECK (rating >= 0 AND rating <= 5),
    reviews INTEGER DEFAULT 0 CHECK (reviews >= 0),
    in_stock BOOLEAN DEFAULT TRUE,
    stock INTEGER DEFAULT 0 CHECK (stock >= 0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Product Features Table
CREATE TABLE IF NOT EXISTS product_features (
    id SERIAL PRIMARY KEY,
    product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    feature TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(product_id, feature)
);

-- Product Colors Table
CREATE TABLE IF NOT EXISTS product_colors (
    id SERIAL PRIMARY KEY,
    product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    color TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(product_id, color)
);

-- Product Sizes Table
CREATE TABLE IF NOT EXISTS product_sizes (
    id SERIAL PRIMARY KEY,
    product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    size TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(product_id, size)
);

-- =====================================================
-- CUSTOMERS TABLE
-- =====================================================

CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    phone TEXT,
    address TEXT,
    city TEXT,
    country TEXT,
    postal_code TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- ORDERS TABLE
-- =====================================================

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number TEXT UNIQUE NOT NULL,
    customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
    total_amount DECIMAL(10, 2) NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded')),
    payment_status TEXT DEFAULT 'pending' CHECK (payment_status IN ('pending', 'paid', 'failed', 'refunded')),
    shipping_address JSONB,
    billing_address JSONB,
    notes TEXT,
    tracking_number TEXT,
    shipped_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Order Items Table
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    quantity INT NOT NULL CHECK (quantity > 0),
    price DECIMAL(10, 2) NOT NULL CHECK (price >= 0),
    total DECIMAL(10, 2) GENERATED ALWAYS AS (quantity * price) STORED,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- FILE STORAGE METADATA
-- =====================================================

CREATE TABLE file_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name TEXT NOT NULL,
    file_path TEXT NOT NULL,
    file_size BIGINT NOT NULL,
    mime_type TEXT NOT NULL,
    bucket_id TEXT NOT NULL DEFAULT 'uploads',
    owner_id TEXT, -- Can be user_id, product_id, etc.
    owner_type TEXT NOT NULL DEFAULT 'user', -- 'user', 'product', 'category', etc.
    is_public BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- INDEXES FOR PERFORMANCE
-- =====================================================

-- Admin indexes
CREATE INDEX idx_admins_username ON admins(username);
CREATE INDEX idx_admins_email ON admins(email);
CREATE INDEX idx_admins_role ON admins(role);
CREATE INDEX idx_admins_is_active ON admins(is_active);
CREATE INDEX idx_admin_sessions_token ON admin_sessions(session_token);
CREATE INDEX idx_admin_sessions_admin_id ON admin_sessions(admin_id);
CREATE INDEX idx_admin_sessions_expires_at ON admin_sessions(expires_at);
CREATE INDEX idx_admin_activity_admin_id ON admin_activity_log(admin_id);
CREATE INDEX idx_admin_activity_action ON admin_activity_log(action);
CREATE INDEX idx_admin_activity_entity ON admin_activity_log(entity_type, entity_id);
CREATE INDEX idx_admin_activity_created_at ON admin_activity_log(created_at);

-- Categories indexes
CREATE INDEX idx_categories_name ON categories(name);
CREATE INDEX idx_categories_status ON categories(status);
CREATE INDEX idx_categories_created_at ON categories(created_at);

-- Products indexes
CREATE INDEX idx_products_category_id ON products(category_id);
CREATE INDEX idx_products_name ON products(name);
CREATE INDEX idx_products_price ON products(price);
CREATE INDEX idx_products_in_stock ON products(in_stock);
CREATE INDEX idx_products_created_at ON products(created_at);
CREATE INDEX idx_product_features_product_id ON product_features(product_id);
CREATE INDEX idx_product_colors_product_id ON product_colors(product_id);
CREATE INDEX idx_product_sizes_product_id ON product_sizes(product_id);

-- Customers indexes
CREATE INDEX idx_customers_email ON customers(email);
CREATE INDEX idx_customers_name ON customers(name);

-- Orders indexes
CREATE INDEX idx_orders_customer_id ON orders(customer_id);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_created_at ON orders(created_at);
CREATE INDEX idx_orders_order_number ON orders(order_number);
CREATE INDEX idx_order_items_order_id ON order_items(order_id);
CREATE INDEX idx_order_items_product_id ON order_items(product_id);

-- File metadata indexes
CREATE INDEX idx_file_metadata_owner_id ON file_metadata(owner_id);
CREATE INDEX idx_file_metadata_file_path ON file_metadata(file_path);
CREATE INDEX idx_file_metadata_bucket_id ON file_metadata(bucket_id);
CREATE INDEX idx_file_metadata_owner_type ON file_metadata(owner_type);
CREATE INDEX idx_file_metadata_created_at ON file_metadata(created_at);

-- =====================================================
-- TRIGGERS FOR UPDATED_AT COLUMNS
-- =====================================================

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Function to update updated_at_tz timestamp
CREATE OR REPLACE FUNCTION update_updated_at_tz_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Triggers for admin tables
CREATE TRIGGER update_admins_updated_at 
    BEFORE UPDATE ON admins 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Triggers for categories
CREATE TRIGGER update_categories_updated_at 
    BEFORE UPDATE ON categories 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Triggers for products
CREATE TRIGGER update_products_updated_at 
    BEFORE UPDATE ON products 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Triggers for customers
CREATE TRIGGER update_customers_updated_at 
    BEFORE UPDATE ON customers 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_tz_column();

-- Triggers for orders
CREATE TRIGGER update_orders_updated_at 
    BEFORE UPDATE ON orders 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_tz_column();

-- Triggers for file metadata
CREATE TRIGGER update_file_metadata_updated_at 
    BEFORE UPDATE ON file_metadata 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_tz_column();

-- =====================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- =====================================================

-- Enable RLS on tables that need it
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE file_metadata ENABLE ROW LEVEL SECURITY;

-- Customers policies - allow public access
CREATE POLICY "Public can view customers" ON customers FOR SELECT USING (true);
CREATE POLICY "Public can insert customers" ON customers FOR INSERT WITH CHECK (true);
CREATE POLICY "Public can update customers" ON customers FOR UPDATE USING (true);
CREATE POLICY "Public can delete customers" ON customers FOR DELETE USING (true);

-- Orders policies - allow public access
CREATE POLICY "Public can view orders" ON orders FOR SELECT USING (true);
CREATE POLICY "Public can insert orders" ON orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Public can update orders" ON orders FOR UPDATE USING (true);
CREATE POLICY "Public can delete orders" ON orders FOR DELETE USING (true);

-- Order items policies - allow public access
CREATE POLICY "Public can view order items" ON order_items FOR SELECT USING (true);
CREATE POLICY "Public can insert order items" ON order_items FOR INSERT WITH CHECK (true);
CREATE POLICY "Public can update order items" ON order_items FOR UPDATE USING (true);
CREATE POLICY "Public can delete order items" ON order_items FOR DELETE USING (true);

-- File metadata policies - allow public access for simplicity
CREATE POLICY "Allow all file metadata views" ON file_metadata FOR SELECT USING (true);
CREATE POLICY "Allow all file metadata uploads" ON file_metadata FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all file metadata updates" ON file_metadata FOR UPDATE USING (true);
CREATE POLICY "Allow all file metadata deletes" ON file_metadata FOR DELETE USING (true);

-- =====================================================
-- STORAGE BUCKET SETUP
-- =====================================================

-- Create storage bucket for uploads
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'uploads', 
    'uploads', 
    true, 
    52428800, -- 50MB limit
    ARRAY['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'application/pdf']
) ON CONFLICT (id) DO NOTHING;

-- Storage policies for uploads bucket
DROP POLICY IF EXISTS "Public read uploads" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated upload to uploads" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated update uploads" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated delete uploads" ON storage.objects;

CREATE POLICY "Public read uploads"
ON storage.objects
FOR SELECT
USING (bucket_id = 'uploads');

CREATE POLICY "Authenticated upload to uploads"
ON storage.objects
FOR INSERT
WITH CHECK (
  bucket_id = 'uploads'
  AND auth.role() = 'authenticated'
);

CREATE POLICY "Authenticated update uploads"
ON storage.objects
FOR UPDATE
USING (
  bucket_id = 'uploads'
  AND auth.role() = 'authenticated'
)
WITH CHECK (
  bucket_id = 'uploads'
  AND auth.role() = 'authenticated'
);

CREATE POLICY "Authenticated delete uploads"
ON storage.objects
FOR DELETE
USING (
  bucket_id = 'uploads'
  AND auth.role() = 'authenticated'
);

-- =====================================================
-- SAMPLE DATA INSERTION
-- =====================================================

-- Insert default admin user (password: admin123)
INSERT INTO admins (username, email, password_hash, full_name, role) VALUES
('admin', 'admin@anybox.com', '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj6hsxq9w5KS', 'Super Administrator', 'super_admin')
ON CONFLICT (username) DO NOTHING;

-- Insert sample categories
INSERT INTO categories (id, name, description, status) VALUES
(0, 'All', 'Default category for uncategorized products', 'inactive'),
(1, 'Electronics', 'Electronic devices and accessories', 'active'),
(2, 'Clothing', 'Fashion and apparel items', 'active'),
(3, 'Books', 'Books and educational materials', 'active'),
(4, 'Home & Garden', 'Home decoration and garden supplies', 'active'),
(5, 'Sports & Outdoors', 'Sports equipment and outdoor gear', 'active')
ON CONFLICT (id) DO NOTHING;

-- =====================================================
-- TRIGGER FOR AUTOMATIC PRODUCT REASSIGNMENT
-- =====================================================

-- Function to reassign products when category is deleted
CREATE OR REPLACE FUNCTION reassign_products_on_category_delete()
RETURNS TRIGGER AS $$
BEGIN
    -- When a category is deleted, reassign its products to the "All" category (id = 0)
    -- Don't trigger for the "All" category itself
    IF OLD.id != 0 THEN
        UPDATE products 
        SET category_id = 0 
        WHERE category_id = OLD.id;
    END IF;
    
    RETURN OLD;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to automatically reassign products when category is deleted
DROP TRIGGER IF EXISTS category_delete_reassign ON categories;
CREATE TRIGGER category_delete_reassign
BEFORE DELETE ON categories
FOR EACH ROW
EXECUTE FUNCTION reassign_products_on_category_delete();

-- Insert sample customers
INSERT INTO customers (name, email, phone, address, city, country, postal_code) VALUES
('John Doe', 'john.doe@example.com', '+1-555-0123', '123 Main St', 'New York', 'USA', '10001'),
('Jane Smith', 'jane.smith@example.com', '+1-555-0124', '456 Oak Ave', 'Los Angeles', 'USA', '90001'),
('Bob Johnson', 'bob.johnson@example.com', '+1-555-0125', '789 Pine Rd', 'Chicago', 'USA', '60007'),
('Alice Brown', 'alice.brown@example.com', '+1-555-0126', '321 Elm St', 'Houston', 'USA', '77002'),
('Charlie Wilson', 'charlie.wilson@example.com', '+1-555-0127', '654 Maple Dr', 'Phoenix', 'USA', '85001')
ON CONFLICT (email) DO NOTHING;

-- Insert sample products
INSERT INTO products (id, name, description, price, category_id, subcategory, image, rating, reviews, in_stock, stock) VALUES
('lp-001', 'Laptop Pro 15"', 'High-performance laptop with 15" display', 1299.99, 1, 'Laptops', '/images/laptop-pro-15.jpg', 4.5, 128, true, 50),
('lp-002', 'Laptop Air 13"', 'Ultra-light laptop with 13" display', 1799.99, 1, 'Laptops', '/images/laptop-air-13.jpg', 4.7, 89, true, 30),
('sp-001', 'Smartphone X', 'Latest flagship smartphone', 999.99, 1, 'Smartphones', '/images/smartphone-x.jpg', 4.3, 256, true, 100),
('sp-002', 'Smartphone Y', 'Mid-range smartphone', 1099.99, 1, 'Smartphones', '/images/smartphone-y.jpg', 4.1, 167, true, 75),
('tv-001', 'Smart TV 55"', '4K Smart TV with HDR', 1499.99, 1, 'Televisions', '/images/smart-tv-55.jpg', 4.6, 78, true, 25)
ON CONFLICT (id) DO NOTHING;

-- Insert sample orders
INSERT INTO orders (order_number, customer_id, total_amount, status, payment_status, shipping_address, billing_address, notes) VALUES
('ORD-001', 1, 1299.99, 'delivered', 'paid', '{"street": "123 Main St", "city": "New York", "country": "USA", "postal_code": "10001"}', '{"street": "123 Main St", "city": "New York", "country": "USA", "postal_code": "10001"}', 'Delivered on time'),
('ORD-002', 2, 999.99, 'shipped', 'paid', '{"street": "456 Oak Ave", "city": "Los Angeles", "country": "USA", "postal_code": "90001"}', '{"street": "456 Oak Ave", "city": "Los Angeles", "country": "USA", "postal_code": "90001"}', 'In transit'),
('ORD-003', 3, 1799.99, 'processing', 'pending', '{"street": "789 Pine Rd", "city": "Chicago", "country": "USA", "postal_code": "60007"}', '{"street": "789 Pine Rd", "city": "Chicago", "country": "USA", "postal_code": "60007"}', 'Processing order'),
('ORD-004', 4, 1099.99, 'delivered', 'paid', '{"street": "321 Elm St", "city": "Houston", "country": "USA", "postal_code": "77002"}', '{"street": "321 Elm St", "city": "Houston", "country": "USA", "postal_code": "77002"}', 'Delivered'),
('ORD-005', 5, 1499.99, 'pending', 'pending', '{"street": "654 Maple Dr", "city": "Phoenix", "country": "USA", "postal_code": "85001"}', '{"street": "654 Maple Dr", "city": "Phoenix", "country": "USA", "postal_code": "85001"}', 'New order')
ON CONFLICT (order_number) DO NOTHING;

-- Insert sample order items
INSERT INTO order_items (order_id, product_id, quantity, price) VALUES
(1, 'lp-001', 1, 1299.99),
(2, 'sp-001', 1, 999.99),
(3, 'lp-002', 1, 1799.99),
(4, 'sp-002', 1, 1099.99),
(2, 'tv-001', 1, 1499.99)
ON CONFLICT DO NOTHING;

-- Insert sample file metadata
INSERT INTO file_metadata (file_name, file_path, file_size, mime_type, bucket_id, owner_id, owner_type, is_public) VALUES
('product-image-1.jpg', 'uploads/product-image-1.jpg', 1024000, 'image/jpeg', 'uploads', 'lp-001', 'product', true),
('user-avatar-1.png', 'uploads/user-avatar-1.png', 51200, 'image/png', 'uploads', 'admin', 'user', false),
('category-banner-1.jpg', 'uploads/category-banner-1.jpg', 204800, 'image/jpeg', 'uploads', '1', 'category', true)
ON CONFLICT DO NOTHING;

-- =====================================================
-- USEFUL VIEWS
-- =====================================================

-- View for products with category details
CREATE OR REPLACE VIEW products_with_category AS
SELECT 
    p.*,
    c.name as category_name,
    c.status as category_status,
    COALESCE(
        json_agg(
            json_build_object('feature', pf.feature)
        ) FILTER (WHERE pf.feature IS NOT NULL), 
        '[]'::json
    ) as features,
    COALESCE(
        json_agg(
            json_build_object('color', pc.color)
        ) FILTER (WHERE pc.color IS NOT NULL), 
        '[]'::json
    ) as colors,
    COALESCE(
        json_agg(
            json_build_object('size', ps.size)
        ) FILTER (WHERE ps.size IS NOT NULL), 
        '[]'::json
    ) as sizes
FROM products p
LEFT JOIN categories c ON p.category_id = c.id
LEFT JOIN product_features pf ON p.id = pf.product_id
LEFT JOIN product_colors pc ON p.id = pc.product_id
LEFT JOIN product_sizes ps ON p.id = ps.product_id
GROUP BY p.id, c.name, c.status;

-- View for orders with customer details
CREATE OR REPLACE VIEW orders_with_customer AS
SELECT 
    o.*,
    c.name as customer_name,
    c.email as customer_email,
    c.phone as customer_phone,
    json_agg(
        json_build_object(
            'product_id', oi.product_id,
            'quantity', oi.quantity,
            'price', oi.price,
            'total', oi.total,
            'product_name', p.name
        )
    ) as items
FROM orders o
LEFT JOIN customers c ON o.customer_id = c.id
LEFT JOIN order_items oi ON o.id = oi.order_id
LEFT JOIN products p ON oi.product_id = p.id
GROUP BY o.id, c.name, c.email, c.phone;

-- View for categories with product count
CREATE OR REPLACE VIEW categories_with_product_count AS
SELECT 
    c.*,
    COUNT(p.id) as product_count
FROM categories c
LEFT JOIN products p ON c.id = p.category_id
GROUP BY c.id, c.name, c.description, c.image_url, c.status, c.created_at, c.updated_at
ORDER BY c.name;

-- =====================================================
-- COMPLETE DATABASE SCHEMA
-- =====================================================
-- This schema includes:
-- 1. Admin management (admins, sessions, activity logs)
-- 2. Product catalog (products, categories, features, colors, sizes)
-- 3. Order management (customers, orders, order items)
-- 4. File storage (file metadata, storage buckets)
-- 5. Proper indexes, triggers, RLS policies
-- 6. Sample data for testing
-- 7. Useful views for common queries
-- =====================================================
