-- =====================================================
-- Orders Database Schema for E-Commerce Application
-- =====================================================
-- Run this in your Supabase SQL Editor
-- =====================================================

-- =====================================================
-- TABLE CREATION
-- =====================================================

-- Customers Table
CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    phone TEXT,
    address TEXT,
    city TEXT,
    country TEXT,
    postal_code TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Orders Table
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number TEXT UNIQUE NOT NULL,
    customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
    total_amount DECIMAL(10, 2) NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded')),
    payment_status TEXT DEFAULT 'pending' CHECK (payment_status IN ('pending', 'paid', 'failed', 'refunded')),
    shipping_address JSONB,
    billing_address JSONB,
    notes TEXT,
    tracking_number TEXT,
    shipped_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Order Items Table
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    quantity INT NOT NULL CHECK (quantity > 0),
    price DECIMAL(10, 2) NOT NULL CHECK (price >= 0),
    total DECIMAL(10, 2) GENERATED ALWAYS AS (quantity * price) STORED,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- INDEXES FOR PERFORMANCE
-- =====================================================

-- Index for faster order lookups
CREATE INDEX idx_orders_customer_id ON orders(customer_id);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_created_at ON orders(created_at);
CREATE INDEX idx_orders_order_number ON orders(order_number);

-- Index for order items
CREATE INDEX idx_order_items_order_id ON order_items(order_id);
CREATE INDEX idx_order_items_product_id ON order_items(product_id);

-- Index for customers
CREATE INDEX idx_customers_email ON customers(email);
CREATE INDEX idx_customers_name ON customers(name);

-- =====================================================
-- RLS (Row Level Security) POLICIES
-- =====================================================

-- Enable RLS on all tables
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

-- Customers policies - allow public read access
CREATE POLICY "Public can view customers" ON customers FOR SELECT USING (true);
CREATE POLICY "Public can insert customers" ON customers FOR INSERT WITH CHECK (true);
CREATE POLICY "Public can update customers" ON customers FOR UPDATE USING (true);
CREATE POLICY "Public can delete customers" ON customers FOR DELETE USING (true);

-- Orders policies - allow public read access
CREATE POLICY "Public can view orders" ON orders FOR SELECT USING (true);
CREATE POLICY "Public can insert orders" ON orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Public can update orders" ON orders FOR UPDATE USING (true);
CREATE POLICY "Public can delete orders" ON orders FOR DELETE USING (true);

-- Order items policies - allow public read access
CREATE POLICY "Public can view order items" ON order_items FOR SELECT USING (true);
CREATE POLICY "Public can insert order items" ON order_items FOR INSERT WITH CHECK (true);
CREATE POLICY "Public can update order items" ON order_items FOR UPDATE USING (true);
CREATE POLICY "Public can delete order items" ON order_items FOR DELETE USING (true);

-- =====================================================
-- TRIGGERS FOR UPDATED_AT
-- =====================================================

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Triggers for updated_at
CREATE TRIGGER update_customers_updated_at 
    BEFORE UPDATE ON customers 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_orders_updated_at 
    BEFORE UPDATE ON orders 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- SAMPLE DATA INSERTION
-- =====================================================

-- Sample Customers
INSERT INTO customers (name, email, phone, address, city, country, postal_code) VALUES
('John Doe', 'john.doe@example.com', '+1-555-0123', '123 Main St', 'New York', 'USA', '10001'),
('Jane Smith', 'jane.smith@example.com', '+1-555-0124', '456 Oak Ave', 'Los Angeles', 'USA', '90001'),
('Bob Johnson', 'bob.johnson@example.com', '+1-555-0125', '789 Pine Rd', 'Chicago', 'USA', '60007'),
('Alice Brown', 'alice.brown@example.com', '+1-555-0126', '321 Elm St', 'Houston', 'USA', '77002'),
('Charlie Wilson', 'charlie.wilson@example.com', '+1-555-0127', '654 Maple Dr', 'Phoenix', 'USA', '85001');

-- Sample Orders
INSERT INTO orders (order_number, customer_id, total_amount, status, payment_status, shipping_address, billing_address, notes) VALUES
('ORD-001', 1, 1299.99, 'delivered', 'paid', '{"street": "123 Main St", "city": "New York", "country": "USA", "postal_code": "10001"}', '{"street": "123 Main St", "city": "New York", "country": "USA", "postal_code": "10001"}', 'Delivered on time'),
('ORD-002', 2, 999.99, 'shipped', 'paid', '{"street": "456 Oak Ave", "city": "Los Angeles", "country": "USA", "postal_code": "90001"}', '{"street": "456 Oak Ave", "city": "Los Angeles", "country": "USA", "postal_code": "90001"}', 'In transit'),
('ORD-003', 3, 1799.99, 'processing', 'pending', '{"street": "789 Pine Rd", "city": "Chicago", "country": "USA", "postal_code": "60007"}', '{"street": "789 Pine Rd", "city": "Chicago", "country": "USA", "postal_code": "60007"}', 'Processing order'),
('ORD-004', 4, 1099.99, 'delivered', 'paid', '{"street": "321 Elm St", "city": "Houston", "country": "USA", "postal_code": "77002"}', '{"street": "321 Elm St", "city": "Houston", "country": "USA", "postal_code": "77002"}', 'Delivered'),
('ORD-005', 5, 1499.99, 'pending', 'pending', '{"street": "654 Maple Dr", "city": "Phoenix", "country": "USA", "postal_code": "85001"}', '{"street": "654 Maple Dr", "city": "Phoenix", "country": "USA", "postal_code": "85001"}', 'New order');

-- Sample Order Items
INSERT INTO order_items (order_id, product_id, quantity, price) VALUES
(1, 'lp-001', 1, 1299.99),
(2, 'sp-001', 1, 999.99),
(3, 'lp-002', 1, 1799.99),
(4, 'sp-002', 1, 1099.99),
(2, 'tv-001', 1, 1499.99);

-- =====================================================
-- SETUP COMPLETE
-- =====================================================
