-- Create about_banner table
CREATE TABLE IF NOT EXISTS about_banner (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    subtitle TEXT,
    description TEXT NOT NULL,
    image TEXT,
    button_text TEXT,
    button_link TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE
);

-- Create index for better performance
CREATE INDEX IF NOT EXISTS idx_about_banner_active ON about_banner(is_active);

-- Enable RLS (Row Level Security)
ALTER TABLE about_banner ENABLE ROW LEVEL SECURITY;

-- Create RLS policies - simplified for all authenticated users
CREATE POLICY "Allow read access for all authenticated users" ON about_banner
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Allow insert for authenticated users" ON about_banner
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow update for authenticated users" ON about_banner
    FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Allow delete for authenticated users" ON about_banner
    FOR DELETE USING (auth.role() = 'authenticated');

-- Create trigger for updated_at
CREATE OR REPLACE FUNCTION handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER handle_about_banner_updated_at
    BEFORE UPDATE ON about_banner
    FOR EACH ROW
    EXECUTE FUNCTION handle_updated_at();
