-- =====================================================
-- Products Database Schema for E-Commerce Application
-- =====================================================
-- Run this in your Supabase SQL Editor
-- =====================================================

-- =====================================================
-- PRODUCT TABLE CREATION
-- =====================================================

-- Products Table
CREATE TABLE IF NOT EXISTS products (
    id TEXT PRIMARY KEY, -- Product ID as string (e.g., 'lp-001', 'sp-001')
    name TEXT NOT NULL,
    slug TEXT UNIQUE, -- URL-friendly slug
    description TEXT,
    price DECIMAL(10, 2) NOT NULL CHECK (price >= 0),
    category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,
    subcategory TEXT,
    image TEXT,
    gallery_images TEXT[], -- Array of gallery image URLs
    rating DECIMAL(3, 2) DEFAULT 0 CHECK (rating >= 0 AND rating <= 5),
    reviews INTEGER DEFAULT 0 CHECK (reviews >= 0),
    in_stock BOOLEAN DEFAULT TRUE,
    stock INTEGER DEFAULT 0 CHECK (stock >= 0),
    features TEXT[], -- Array of product features (denormalized for easier access
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Product Features Table (for detailed feature management)
CREATE TABLE IF NOT EXISTS product_features (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    feature TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(product_id, feature)
);

-- Product Colors Table
CREATE TABLE IF NOT EXISTS product_colors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    color TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(product_id, color)
);

-- Product Sizes Table
CREATE TABLE IF NOT EXISTS product_sizes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    size TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(product_id, size)
);

-- =====================================================
-- INDEXES FOR PRODUCT TABLES
-- =====================================================

-- Products indexes
CREATE INDEX IF NOT EXISTS idx_products_category_id ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_name ON products(name);
CREATE INDEX IF NOT EXISTS idx_products_slug ON products(slug);
CREATE INDEX IF NOT EXISTS idx_products_price ON products(price);
CREATE INDEX IF NOT EXISTS idx_products_in_stock ON products(in_stock);
CREATE INDEX IF NOT EXISTS idx_products_created_at ON products(created_at);

-- Feature, color, and size indexes
CREATE INDEX IF NOT EXISTS idx_product_features_product_id ON product_features(product_id);
CREATE INDEX IF NOT EXISTS idx_product_colors_product_id ON product_colors(product_id);
CREATE INDEX IF NOT EXISTS idx_product_sizes_product_id ON product_sizes(product_id);

-- =====================================================
-- TRIGGERS FOR UPDATED_AT
-- =====================================================

-- Function to update updated_at column
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger for products table
DROP TRIGGER IF EXISTS update_products_updated_at ON products;
CREATE TRIGGER update_products_updated_at 
    BEFORE UPDATE ON products 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- RLS (ROW LEVEL SECURITY) POLICIES
-- =====================================================

-- Enable RLS on products
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- Products policies
CREATE POLICY "Products are viewable by everyone" ON products
    FOR SELECT USING (true);

CREATE POLICY "Admins can insert products" ON products
    FOR INSERT WITH CHECK (auth.jwt() ->> 'role' = 'admin');

CREATE POLICY "Admins can update products" ON products
    FOR UPDATE USING (auth.jwt() ->> 'role' = 'admin');

CREATE POLICY "Admins can delete products" ON products
    FOR DELETE USING (auth.jwt() ->> 'role' = 'admin');

-- Enable RLS on related tables
ALTER TABLE product_features ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_colors ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_sizes ENABLE ROW LEVEL SECURITY;

-- Related tables policies
CREATE POLICY "Product features are viewable by everyone" ON product_features
    FOR SELECT USING (true);

CREATE POLICY "Admins can manage product features" ON product_features
    FOR ALL USING (auth.jwt() ->> 'role' = 'admin');

CREATE POLICY "Product colors are viewable by everyone" ON product_colors
    FOR SELECT USING (true);

CREATE POLICY "Admins can manage product colors" ON product_colors
    FOR ALL USING (auth.jwt() ->> 'role' = 'admin');

CREATE POLICY "Product sizes are viewable by everyone" ON product_sizes
    FOR SELECT USING (true);

CREATE POLICY "Admins can manage product sizes" ON product_sizes
    FOR ALL USING (auth.jwt() ->> 'role' = 'admin');

-- =====================================================
-- SAMPLE DATA (Optional)
-- =====================================================

-- Insert sample products (optional - remove if not needed)
/*
INSERT INTO products (id, name, slug, description, price, category_id, subcategory, image, gallery_images, rating, reviews, in_stock, stock, features) VALUES
('lp-001', 'Laptop Pro 15"', 'laptop-pro-15', 'High-performance laptop with 15" display', 1299.99, 1, 'Laptops', '/images/laptop-pro-15.jpg', ARRAY['/images/laptop-pro-15-1.jpg', '/images/laptop-pro-15-2.jpg'], 4.5, 128, true, 50, ARRAY['15" Display', 'Intel Core i7', '16GB RAM', '512GB SSD']),
('lp-002', 'Laptop Air 13"', 'laptop-air-13', 'Ultra-light laptop with 13" display', 1799.99, 1, 'Laptops', '/images/laptop-air-13.jpg', ARRAY['/images/laptop-air-13-1.jpg', '/images/laptop-air-13-2.jpg'], 4.7, 89, true, 30, ARRAY['13" Display', 'Apple M2', '8GB RAM', '256GB SSD']),
('sp-001', 'Smartphone X', 'smartphone-x', 'Latest flagship smartphone', 999.99, 1, 'Smartphones', '/images/smartphone-x.jpg', ARRAY['/images/smartphone-x-1.jpg', '/images/smartphone-x-2.jpg'], 4.3, 256, true, 100, ARRAY['6.1" Display', '5G Connectivity', '128GB Storage', 'Dual Camera']);
*/
