-- =====================================================
-- Storage Bucket Schema for File Uploads
-- =====================================================
-- Run this in your Supabase SQL Editor to enable file storage
-- =====================================================

-- =====================================================
-- STORAGE BUCKET SETUP
-- =====================================================

-- Create a storage bucket for uploads
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'uploads', 
    'uploads', 
    true, 
    52428800, -- 50MB limit
    ARRAY['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'application/pdf']
) ON CONFLICT (id) DO NOTHING;

-- =====================================================
-- FILE METADATA TABLE
-- =====================================================

-- Table to track file metadata and permissions
CREATE TABLE file_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name TEXT NOT NULL,
    file_path TEXT NOT NULL,
    file_size BIGINT NOT NULL,
    mime_type TEXT NOT NULL,
    bucket_id TEXT NOT NULL DEFAULT 'uploads',
    owner_id TEXT, -- Can be user_id, product_id, etc.
    owner_type TEXT NOT NULL DEFAULT 'user', -- 'user', 'product', 'category', etc.
    is_public BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- RLS (Row Level Security) POLICIES
-- =====================================================

-- Enable RLS on file metadata table
ALTER TABLE file_metadata ENABLE ROW LEVEL SECURITY;

-- Policy for public file access
CREATE POLICY "Users can view their own files" ON file_metadata FOR SELECT USING (
    auth.uid()::text = owner_id::text
);

-- Policy for file uploads
CREATE POLICY "Users can upload files" ON file_metadata FOR INSERT WITH CHECK (
    auth.uid()::text = owner_id::text
);

-- Policy for file updates
CREATE POLICY "Users can update their own files" ON file_metadata FOR UPDATE USING (
    auth.uid()::text = owner_id::text
);

-- Policy for file deletions
CREATE POLICY "Users can delete their own files" ON file_metadata FOR DELETE USING (
    auth.uid()::text = owner_id::text
);

-- Policy for public access (if needed)
CREATE POLICY "Public files are viewable by everyone" ON file_metadata FOR SELECT USING (
    is_public = true
);

-- =====================================================
-- INDEXES FOR PERFORMANCE
-- =====================================================

-- Index for owner lookups
CREATE INDEX idx_file_metadata_owner_id ON file_metadata(owner_id);

-- Index for file path lookups
CREATE INDEX idx_file_metadata_file_path ON file_metadata(file_path);

-- Index for bucket filtering
CREATE INDEX idx_file_metadata_bucket_id ON file_metadata(bucket_id);

-- Index for owner type filtering
CREATE INDEX idx_file_metadata_owner_type ON file_metadata(owner_type);

-- Index for created at
CREATE INDEX idx_file_metadata_created_at ON file_metadata(created_at);

-- =====================================================
-- SAMPLE DATA (Optional)
-- =====================================================

-- Sample file metadata entries (for testing)
INSERT INTO file_metadata (file_name, file_path, file_size, mime_type, bucket_id, owner_id, owner_type, is_public) VALUES
('product-image-1.jpg', 'uploads/product-image-1.jpg', 1024000, 'image/jpeg', 'uploads', 'prod-001', 'product', true),
('user-avatar-1.png', 'uploads/user-avatar-1.png', 51200, 'image/png', 'uploads', 'user-123', 'user', false),
('category-banner-1.jpg', 'uploads/category-banner-1.jpg', 204800, 'image/jpeg', 'uploads', 'cat-laptops', 'category', true);

-- =====================================================
-- SETUP COMPLETE
-- =====================================================
